version: '3.7'

services:
  web:
    build: .
    command: gunicorn booktime.wsgi:application --bind 0.0.0.0:8000 --pythonpath /booktime_project/booktime
    volumes:
      - static_volume:/booktime_project/booktime/staticfiles
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/booktime_project/booktime/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: