version: '3.7'

services:
  web:
    build: .
    image: ${REGISTRY_HOST}/booktime:v1.0.0
    command: python booktime/manage.py test main.tests
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - REGISTRY_HOST