version: '3.7'

services:
  web:
    build: .
    command: python booktime/manage.py runserver 0.0.0.0:8000
    ports:
      - 8888:8000
    environment:
      - DJANGO_DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS